# Generated by Django 5.2.1 on 2025-05-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_cat_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_img',
            field=models.ImageField(blank=True, null=True, upload_to='photos/categories'),
        ),
    ]
