# Generated by Django 5.2.1 on 2025-05-28 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_cat_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
